import { create } from 'zustand';

export const useStore = create((set, get) => ({
  sessions: [],
  currentSession: null,
  messages: [],
  input: "",
  models: [],
  selectedPersonaIds: [],
  selectedModelSingle: undefined,
  interactionMode: "Normal",
  isAgentTerminalActive: false,
  activeView: 'chat',
  webMode: false,
  ragMode: false,
  unrestrictedMode: false,
  selectedNode: null,
  editNodeText: "",
  isSyncingMemory: false,
  darkMode: localStorage.getItem('parthenope_dark') === 'true',
  sidebarWidth: parseInt(localStorage.getItem('parthenope_sidebar_w') || '240'),
  diagnosticsWidth: parseInt(localStorage.getItem('parthenope_diag_w') || '360'),
  lastUserMessage: null,
  copiedMsgId: null,
  isRegenerating: false,
  showModelDropdown: false,
  showJudgeDropdown: false,
  uploadStatus: "",
  debateTurns: 2,
  judgePersonaId: "",
  isStreaming: false,
  streamingBlocks: [],
  terminalLogs: [],
  sessionFiles: [],
  pipelineStatus: null,
  metrics: { latency: 0, tokens: 0, vram: "0GB", tps: 0 },
  sysStats: { cpu: 0, ram: 0, vram: 0, details: {} },
  scrollLock: true,
  visionBuffer: [],
  isListening: false,
  activeTerminalTab: "LOGS",
  synapsePreset: "code-review",
  synapsePresets: [],
  autoRead: false,
  selectedVoice: "male_us",
  personas: [],
  selectedPersonaId: "",
  personaMap: {},
  scenarios: [],
  selectedScenarioId: "",
  showPersonaForge: false,
  editingPersona: null,
  forgeTab: "settings",
  moodHistory: [],
  heatmapEnabled: false,
  showUserProfile: false,
  personaMood: null,
  pendingTrigger: null,
  showScenarioBuilder: false,
  editingScenario: null,
  hiddenIntents: {},
  roleModelMap: {},
  evaluation: null,
  isEvaluating: false,
  forgeSaveStatus: "idle",
  simulationChaos: 1.0,
  vectorNodes: [],
  pinnedMemories: [],
  expandedImage: null,
  mapTransform: { x: 0, y: 0, k: 1 },
  isDraggingMap: false,
  dragStart: { x: 0, y: 0 },
  mapHasMoved: false,
  showDbManager: false,
  logs: [],

  setSessions: (val) => set((state) => ({ sessions: typeof val === 'function' ? val(state.sessions) : val })),
  setCurrentSession: (val) => set((state) => ({ currentSession: typeof val === 'function' ? val(state.currentSession) : val })),
  setMessages: (val) => set((state) => ({ messages: typeof val === 'function' ? val(state.messages) : val })),
  setInput: (val) => set((state) => ({ input: typeof val === 'function' ? val(state.input) : val })),
  setModels: (val) => set((state) => ({ models: typeof val === 'function' ? val(state.models) : val })),
  setSelectedPersonaIds: (val) => set((state) => ({ selectedPersonaIds: typeof val === 'function' ? val(state.selectedPersonaIds) : val })),
  setSelectedModelSingle: (val) => set((state) => ({ selectedModelSingle: typeof val === 'function' ? val(state.selectedModelSingle) : val })),
  setInteractionMode: (val) => set((state) => ({ interactionMode: typeof val === 'function' ? val(state.interactionMode) : val })),
  setAgentTerminalActive: (val) => set((state) => ({ isAgentTerminalActive: typeof val === 'function' ? val(state.isAgentTerminalActive) : val })),
  setActiveView: (val) => set((state) => ({ activeView: typeof val === 'function' ? val(state.activeView) : val })),
  setWebMode: (val) => set((state) => ({ webMode: typeof val === 'function' ? val(state.webMode) : val })),
  setRagMode: (val) => set((state) => ({ ragMode: typeof val === 'function' ? val(state.ragMode) : val })),
  setUnrestrictedMode: (val) => set((state) => ({ unrestrictedMode: typeof val === 'function' ? val(state.unrestrictedMode) : val })),
  setSelectedNode: (val) => set((state) => ({ selectedNode: typeof val === 'function' ? val(state.selectedNode) : val })),
  setEditNodeText: (val) => set((state) => ({ editNodeText: typeof val === 'function' ? val(state.editNodeText) : val })),
  setIsSyncingMemory: (val) => set((state) => ({ isSyncingMemory: typeof val === 'function' ? val(state.isSyncingMemory) : val })),
  setDarkMode: (val) => set((state) => ({ darkMode: typeof val === 'function' ? val(state.darkMode) : val })),
  setSidebarWidth: (val) => set((state) => ({ sidebarWidth: typeof val === 'function' ? val(state.sidebarWidth) : val })),
  setDiagnosticsWidth: (val) => set((state) => ({ diagnosticsWidth: typeof val === 'function' ? val(state.diagnosticsWidth) : val })),
  setLastUserMessage: (val) => set((state) => ({ lastUserMessage: typeof val === 'function' ? val(state.lastUserMessage) : val })),
  setCopiedMsgId: (val) => set((state) => ({ copiedMsgId: typeof val === 'function' ? val(state.copiedMsgId) : val })),
  setIsRegenerating: (val) => set((state) => ({ isRegenerating: typeof val === 'function' ? val(state.isRegenerating) : val })),
  setShowModelDropdown: (val) => set((state) => ({ showModelDropdown: typeof val === 'function' ? val(state.showModelDropdown) : val })),
  setShowJudgeDropdown: (val) => set((state) => ({ showJudgeDropdown: typeof val === 'function' ? val(state.showJudgeDropdown) : val })),
  setUploadStatus: (val) => set((state) => ({ uploadStatus: typeof val === 'function' ? val(state.uploadStatus) : val })),
  setDebateTurns: (val) => set((state) => ({ debateTurns: typeof val === 'function' ? val(state.debateTurns) : val })),
  setJudgePersonaId: (val) => set((state) => ({ judgePersonaId: typeof val === 'function' ? val(state.judgePersonaId) : val })),
  setIsStreaming: (val) => set((state) => ({ isStreaming: typeof val === 'function' ? val(state.isStreaming) : val })),
  setStreamingBlocks: (val) => set((state) => ({ streamingBlocks: typeof val === 'function' ? val(state.streamingBlocks) : val })),
  setTerminalLogs: (val) => set((state) => ({ terminalLogs: typeof val === 'function' ? val(state.terminalLogs) : val })),
  setSessionFiles: (val) => set((state) => ({ sessionFiles: typeof val === 'function' ? val(state.sessionFiles) : val })),
  setPipelineStatus: (val) => set((state) => ({ pipelineStatus: typeof val === 'function' ? val(state.pipelineStatus) : val })),
  setMetrics: (val) => set((state) => ({ metrics: typeof val === 'function' ? val(state.metrics) : val })),
  setSysStats: (val) => set((state) => ({ sysStats: typeof val === 'function' ? val(state.sysStats) : val })),
  setScrollLock: (val) => set((state) => ({ scrollLock: typeof val === 'function' ? val(state.scrollLock) : val })),
  setVisionBuffer: (val) => set((state) => ({ visionBuffer: typeof val === 'function' ? val(state.visionBuffer) : val })),
  setIsListening: (val) => set((state) => ({ isListening: typeof val === 'function' ? val(state.isListening) : val })),
  setActiveTerminalTab: (val) => set((state) => ({ activeTerminalTab: typeof val === 'function' ? val(state.activeTerminalTab) : val })),
  setSynapsePreset: (val) => set((state) => ({ synapsePreset: typeof val === 'function' ? val(state.synapsePreset) : val })),
  setSynapsePresets: (val) => set((state) => ({ synapsePresets: typeof val === 'function' ? val(state.synapsePresets) : val })),
  setAutoRead: (val) => set((state) => ({ autoRead: typeof val === 'function' ? val(state.autoRead) : val })),
  setSelectedVoice: (val) => set((state) => ({ selectedVoice: typeof val === 'function' ? val(state.selectedVoice) : val })),
  setPersonas: (val) => set((state) => ({ personas: typeof val === 'function' ? val(state.personas) : val })),
  setSelectedPersonaId: (val) => set((state) => ({ selectedPersonaId: typeof val === 'function' ? val(state.selectedPersonaId) : val })),
  setPersonaMap: (val) => set((state) => ({ personaMap: typeof val === 'function' ? val(state.personaMap) : val })),
  setScenarios: (val) => set((state) => ({ scenarios: typeof val === 'function' ? val(state.scenarios) : val })),
  setSelectedScenarioId: (val) => set((state) => ({ selectedScenarioId: typeof val === 'function' ? val(state.selectedScenarioId) : val })),
  setShowPersonaForge: (val) => set((state) => ({ showPersonaForge: typeof val === 'function' ? val(state.showPersonaForge) : val })),
  setEditingPersona: (val) => set((state) => ({ editingPersona: typeof val === 'function' ? val(state.editingPersona) : val })),
  setForgeTab: (val) => set((state) => ({ forgeTab: typeof val === 'function' ? val(state.forgeTab) : val })),
  setMoodHistory: (val) => set((state) => ({ moodHistory: typeof val === 'function' ? val(state.moodHistory) : val })),
  setHeatmapEnabled: (val) => set((state) => ({ heatmapEnabled: typeof val === 'function' ? val(state.heatmapEnabled) : val })),
  setShowUserProfile: (val) => set((state) => ({ showUserProfile: typeof val === 'function' ? val(state.showUserProfile) : val })),
  setPersonaMood: (val) => set((state) => ({ personaMood: typeof val === 'function' ? val(state.personaMood) : val })),
  setPendingTrigger: (val) => set((state) => ({ pendingTrigger: typeof val === 'function' ? val(state.pendingTrigger) : val })),
  setShowScenarioBuilder: (val) => set((state) => ({ showScenarioBuilder: typeof val === 'function' ? val(state.showScenarioBuilder) : val })),
  setEditingScenario: (val) => set((state) => ({ editingScenario: typeof val === 'function' ? val(state.editingScenario) : val })),
  setHiddenIntents: (val) => set((state) => ({ hiddenIntents: typeof val === 'function' ? val(state.hiddenIntents) : val })),
  setRoleModelMap: (val) => set((state) => ({ roleModelMap: typeof val === 'function' ? val(state.roleModelMap) : val })),
  setEvaluation: (val) => set((state) => ({ evaluation: typeof val === 'function' ? val(state.evaluation) : val })),
  setIsEvaluating: (val) => set((state) => ({ isEvaluating: typeof val === 'function' ? val(state.isEvaluating) : val })),
  setForgeSaveStatus: (val) => set((state) => ({ forgeSaveStatus: typeof val === 'function' ? val(state.forgeSaveStatus) : val })),
  setSimulationChaos: (val) => set((state) => ({ simulationChaos: typeof val === 'function' ? val(state.simulationChaos) : val })),
  setVectorNodes: (val) => set((state) => ({ vectorNodes: typeof val === 'function' ? val(state.vectorNodes) : val })),
  setPinnedMemories: (val) => set((state) => ({ pinnedMemories: typeof val === 'function' ? val(state.pinnedMemories) : val })),
  setExpandedImage: (val) => set((state) => ({ expandedImage: typeof val === 'function' ? val(state.expandedImage) : val })),
  setMapTransform: (val) => set((state) => ({ mapTransform: typeof val === 'function' ? val(state.mapTransform) : val })),
  setIsDraggingMap: (val) => set((state) => ({ isDraggingMap: typeof val === 'function' ? val(state.isDraggingMap) : val })),
  setDragStart: (val) => set((state) => ({ dragStart: typeof val === 'function' ? val(state.dragStart) : val })),
  setMapHasMoved: (val) => set((state) => ({ mapHasMoved: typeof val === 'function' ? val(state.mapHasMoved) : val })),
  setShowDbManager: (val) => set((state) => ({ showDbManager: typeof val === 'function' ? val(state.showDbManager) : val })),
  setLogs: (val) => set((state) => ({ logs: typeof val === 'function' ? val(state.logs) : val })),
}));
